### PR TITLE
Chapter 15

### PR DESCRIPTION
**Pull request by AngelFelizR**

### CODE REVIEW

**Review by jonthegeek — DISMISSED** [review]
Thanks!

**Comment by jonthegeek** [comment]
@AngelFelizR the build threw this error:

```
Quitting from lines 963-993 [regularized-top4-pdp] (bookclub-homl.Rmd)
Error in `grid.arrange()`:
! could not find function "grid.arrange"
```

Check it out and see if you can get it working, please!

**Review by jonthegeek — APPROVED** [review]
If this doesn't build, you'll have to add it to the DESCRIPTION in imports. I can't easily see whether it's already there right now, we should know shortly!

**Comment by AngelFelizR** [comment]
Thanks @jonthegeek your commet really helped to understand the probleem

**Pull request merged**
