### PR TITLE
Add Chapter 3 - Feature & Target Engineering slide notes.

### PR DESCRIPTION
**Pull request by rserran**
Added `forecast` package to DESCRIPTION. Let's give it another try.

### CODE REVIEW

**Review by jonthegeek — DISMISSED** [review]
Thanks! Looks good as long as it builds!

**Comment by rserran** [comment]
Added kableExtra package to DESCRIPTION file. It should run now.

**Review by jonthegeek — DISMISSED** [review]
Thanks! Looks good as long as it builds!

**Review by jonthegeek — APPROVED** [review]
Thanks!

**Pull request merged**
